# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.hostname = "umasds-vm"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "umasds-vm"
    vb.gui = true
    vb.memory = 1024
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "95"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
  end
end
